# Generated by Django 5.2.1 on 2025-06-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_core_produc_categor_ba410e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_transa_status_288ab7_idx',
        ),
    ]
